version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
