php-version = "8.4.0"

[source]
paths = ["app", "tests"]
includes = ["vendor"]
excludes = [
  "./vendor/symfony/cache/Traits/ValueWrapper.php",
  "./vendor/composer",
]

[formatter]
print-width = 180
tab-width = 4
use-tabs = false
null-type-hint = "question"
space-before-arrow-function-parameter-list-parenthesis = true
space-after-logical-not-unary-prefix-operator = true
always-break-named-arguments-list = false
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true
